package com.example.demo.enums;

public enum ProblemeDataEnum {
    CONNEXION_LENTE,
    COUPURES_INTERNET,
    PAS_ACCES_INTERNET,
    FAIBLE_DEBIT,
    APP_SITE_NON_CHARGE,
    PROBLEME_DATA_MOBILE,
    PING_ELEVE,
    DECONNEXION_STREAMING_JEU,
    PROBLEMES_APN,
    DONNEES_EPUISEES,
    PAS_PARTAGE_CONNEXION,
    SIGNAL_WIFI_FAIBLE,
    DEBIT_LIMITE,
    PROBLEME_TELECHARGEMENT,
    BLOCAGE_SITES_APPS
}
