package com.example.demo.enums;

public enum ProblemeVoixEnum {
    APPELS_INTERRUPUS,

    PAS_APPELS,

    RESEAU_INDISPONIBLE,
    PAS_ENTENDU,
    QUALITE_SON_MEDIOCRE,
    ECHO_GRE_SILLEMENT,
    NUMERO_NON_JOIGNABLE,
    CONNEXION_APPEL_LENTE,
    APPELS_PAS_ABOUTIS,
    APPELS_SANS_SONNERIE,
    REPONDEUR_AUTO,
    NUMERO_BLOQUE,
    PROBLEME_INTERNATIONAUX,
    PAS_SMS_ENVOYER,
    ERREUR_RESEAU_APPEL
}
